export const UPDATE_FLATBOND_PERIOD = 'UPDATE_FLATBOND_PERIOD';
export const UPDATE_FLATBOND_POSTCODE = 'UPDATE_FLATBOND_POSTCODE';
export const UPDATE_FLATBOND_VALUE = 'UPDATE_FLATBOND_VALUE';
export const CALCULATE_MEMBERSHIP_FEE = 'CALCULATE_MEMBERSHIP_FEE';
export const RESET_FLATBOND = 'RESET_FLATBOND';

export const GET_CONFIG_START = 'GET_CONFIG_START';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const GET_CONFIG_ERROR = 'GET_CONFIG_ERROR';
