
//DECLARE ALL PERMITED ACTIONS
export const UPDATE_FLATBOND_PERIOD = 'UPDATE_FLATBOND_PERIOD';
export const UPDATE_FLATBOND_POSTCODE = 'UPDATE_FLATBOND_POSTCODE';
export const UPDATE_FLATBOND_AMOUNT = 'UPDATE_FLATBOND_AMOUNT';
export const SET_MEMBERSHIP_FEE = 'SET_MEMBERSHIP_FEE';
export const RESET_FLATBOND = 'RESET_FLATBOND';

export const GET_CONFIG_REQUEST = 'GET_CONFIG_REQUEST';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const GET_CONFIG_ERROR = 'GET_CONFIG_ERROR';
export const RESET_CONFIG = 'RESET_CONFIG';
